### ISSUE TITLE
Sometimes one of the algorithms will return 0 nanoseconds

### ISSUE THREAD

**Issue by submohanty** [submohanty/Algorithm-Timer#5]
Throughout the execution of the code, sometimes you will enter in a word and the code will return 0 nanoseconds. Not pinpointed exactly why.

**Comment by sub7789** [comment]
After the fixes, this issue is only limited to BFS shortest path. Doing debugging as to why.

**Comment by sub7789** [comment]
Latest commit, fixed it by printing out the path from the starting node to the final node.
